version: "{build}"

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 10

branches:
  only:
    - master
    - develop

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_test:
  - node --version
  - npm --version

test_script:
  - npm run lint
  - npm run build
  - npm run build:dev
  - npm run build:prod

build: off

deploy: off
